### ISSUE TITLE
Nacos RefreshScope Can't work on Filter

### ISSUE THREAD

**Issue by gegeza** [alibaba/spring-cloud-alibaba#700] opened 2019-06-10 09:28 UTC
Nacos Discovery
spring-cloud-alibaba.version:**0.9.0**
when i use @RefreshScope on MyFilter(extends OncePerRequestFilter) then :
2019-06-10 17:33:12.451 ERROR 91543 --- [           main] o.s.boot.SpringApplication               : Application run failed
org.springframework.boot.web.server.WebServerException: Unable to start embedded Undertow

**Additional context**
MacOS  、Java8 、 Version 0.9.0.RELEASE

**Comment by Zengqd** [comment] 2019-06-10 09:38
![avatar](http://api.51bnh.com/bfs/1d21a0bd19b34faa946c299bc64172b9.jpg)

**Comment by Zengqd** [comment] 2019-06-10 09:39
the image url: http://api.51bnh.com/bfs/1d21a0bd19b34faa946c299bc64172b9.jpg

**Comment by fangjian0423** [comment] 2019-06-13 02:16
Could you please provide a project that reproduces the issue?

**Comment by fangjian0423** [comment] 2019-09-24 08:05
Closing this issue due to no feedback.

**Closed by fangjian0423** 2019-09-24 08:05 UTC
Labels: nacos
