### ISSUE TITLE
sentinel和spring-web包衝突

### ISSUE THREAD

**Issue by cookiejoo** [alibaba/spring-cloud-alibaba#1074] opened 2019-11-26 08:37 UTC
sentinel1.6.2
使用了spring-cloud-starter-alibaba-sentinel:2.1.0.RELEASE
問題是這樣的,突然某天升級了代碼,發現無法正常接入sentinel
測試過後用-D參數可以正常接入,但是用SpringBoot的properties文件方式無法接入
後面我對比了一下我的包依賴
我的項目包中用到了rabbitMQ,用了spring的依賴,但是我把這個包下的spring-web排除了

org.springframework.amqp
spring-rabbit

org.springframework
spring-web

一个现象是AppNameUtil
public static void resolveAppName() {
        String app = System.getProperty(APP_NAME);
如果不引入spring-web包这里获取不到值,=null,如果引入了spring-web包可以获取到project.name
        // use -Dproject.name first
        if (!isEmpty(app)) {
            appName = app;
            return;
        }

        // parse sun.java.command property
获取不到值则这里是Application启动类的全名
        String command = System.getProperty(SUN_JAVA_COMMAND);
        if (isEmpty(command)) {
            return;
        }

反而導致了sentinel無法正常連接到控制臺.
我把這個包去排除去掉了,必須引入spring-web就可以正常properties文件連接到控制臺.
請幫忙看看是否是包依賴衝突.

https://github.com/alibaba/Sentinel/issues/1178

**Comment by fangjian0423** [comment] 2019-12-02 02:15
what is the version of spring-boot?

**Comment by cookiejoo** [comment] 2019-12-02 02:19
> what is the version of spring-boot?

hello, my vision of spring-boot is: org.springframework.boot:spring-boot-starter:2.1.4.RELEASE

**Comment by fangjian0423** [comment] 2019-12-02 02:22
I don't know why, could you provide a project that reproduces the issue?

branch greenwich is under spring boot 2.1.x and everything is fine: https://github.com/alibaba/spring-cloud-alibaba/tree/greenwich/spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example

**Comment by fangjian0423** [comment] 2019-12-12 11:03
Closing this issue due to no feedback.

**Closed by fangjian0423** 2019-12-12 11:03 UTC
Labels: sentinel
