### ISSUE TITLE
spring-cloud-starter-stream-rocketmq 2.2.7.RELEASE 版本手动ack后无法同步确认offset

### ISSUE THREAD

**Issue by xiaowenyu** [alibaba/spring-cloud-alibaba#2426] opened 2022-03-01 03:53 UTC
组件：
spring-cloud-starter-stream-rocketmq
问题版本：
2.2.7.RELEASE; 2021.0.1.0

问题详情：
stream-rocketmq 2.2.6.RELEASE 升级到 2.2.7.RELEASE 后，无法正常conmit offset 

重现步骤：
1.运行的demo如下，使用 AcknowledgmentCallback.noAutoAck() 关闭自动ack，打印之后再 ack
```
 @Bean
    public ApplicationRunner poller(PollableMessageSource dest1In) {
        return args -> {
            while (true) {
                if (!dest1In.poll(message -> {
                    AcknowledgmentCallback acknowledgmentCallback = StaticMessageHeaderAccessor.getAcknowledgmentCallback(message);
                    acknowledgmentCallback .noAutoAck();
                    if(message.getPayload() instanceof byte[]) {
                        log.info(new String((byte[])message.getPayload()) + " --- received from partition ");
                    }else {
                        log.info(message.getPayload().toString() + " --- received from partition ");
                    }

                    acknowledgmentCallback.acknowledge(AcknowledgmentCallback.Status.ACCEPT);
                })) {
                    Thread.sleep(1000);
                }
            }
        };
    }
```
2. 消费一会后重启demo
3. 2.2.6.RELEASE版本会继续往后消费，不会重复消费，2.2.7.RELEASE从头开始消费，

异常表现
2.2.7.RELEASE版本没有提交确认offset到rocketmq

**Screenshots**
com.alibaba.cloud.stream.binder.rocketmq.integration.RocketMQMessageSource.RocketMQAckCallback#acknowledge 确认offset方式差异，litepullconsumer.committed方法 不支持确认offset到broker
![image](https://user-images.githubusercontent.com/15710646/156101400-7f064489-18ee-49d1-9fe8-eb8cdfd89330.png)

**Additional context**

e.g.  Java8

**Comment by xiaowenyu** [comment] 2022-03-01 04:31
@DanielLiu1123 请问下这个问题会修复吗，预计在哪个版本里面修复

**Comment by DanielLiu1123** [comment] 2022-03-01 04:53
We need to confirm if this is a bug first, if it was, will handle it as soon as possible.

You can try version `2021.0.1.0`.

**Comment by xiaowenyu** [comment] 2022-03-01 06:00
version 2021.0.1.0 has same problem

**Comment by DanielLiu1123** [comment] 2022-03-01 06:06
> version 2021.0.1.0 has same problem

Will look into it.

**Comment by xiaowenyu** [comment] 2022-03-02 04:35
> 
> > version 2021.0.1.0 has same problem
> 
> Will look into it.
what's the result~

**Comment by sollhui** [comment] 2022-06-16 12:28
Please assign to me

**Comment by Sorieee** [comment] 2022-06-17 10:50
Are there multiple brokers in your environment?

**Comment by Sorieee** [comment] 2022-06-17 10:53
I feel it like #2469

**Comment by sollhui** [comment] 2022-06-18 03:34
@steverao the issue is same with #2469 and had been solved, please close it.

**Closed as completed** 2022-06-18 07:02 UTC
Labels: good first issue, area/rocketmq, contribution welcome
